### 2.1 LayerDENSE Object

Now that we create the **_LayerDense_** object which will encode all information about a dense layer in the neural network. We define a _forward_ method for the forward pass on the layer. In the constructor method, we define all class variables which are the weights, biases and output of the layer. Eventually, we will add a _backwards_ method for back propagation. However, for now, we have the following,

In [4]:
import numpy as np

class LayerDense():
    """The LayerDense class implements a dense layer in which all connections from the previous layer are fed to each neuron."""

    def __init__(self, n_inputs, n_neurons):
        """Constuctor method. The weights are initialised with random values between 0 and 1 while we construct
        the biases array as a zero array."""

        # Layer properties,
        self.n_inputs = n_inputs
        self.n_neurons = n_neurons
        self.output = None

        # Initialising layer parameters,
        self.weights = np.random.rand(n_neurons, n_inputs)
        self.biases = np.zeros(n_neurons)
        self.output = None

    def forward(self, input_array):
        """This method defines the forward propagation of the layer."""
        output_array = np.dot(input_array, self.weights.T) + self.biases
        output_array += self.biases
        self.output = output_array
        return None

    def __repr__(self):
        """Useful information for when the user prints the LayDense object."""
        repr_string = f"""Type: DENSE Layer,
        Number of Neurons: {self.n_neurons},
        Expected Input Array: (SAMPLE_SIZE, {self.n_inputs}),
        Output Array Shape: (SAMPLE_SIZE, {self.n_neurons})"""
        return repr_string

### 2.2 Softmax and Sigmoid Activation Functions

The **sigmoid activation function** was the most popular choice for hidden layers before the advent of the ReLU function. Mathematically, the sigmoid activation function is defined below, 

$$ S(x) = \frac{1}{1 + e^{-x}} $$

It as a range of 0 to 1 across a domain of all real numbers. Moving on, the SoftMax activation function is most commonly used in classification problems where we want the neural network to give us a probabilities of a sample belonging to specified labels.

In [5]:
import numpy as np

class ReLU():
    """This is the rectified linear unit (ReLU) which is one of the most common activiation functions
    used in machine learning."""

    def __init__(self):
        self.output = None

    def forward(self, x):
        self.output = np.maximum(0, x)
        return True

class Sigmoid():
    """This is the sigmoid activation function. It scales the input value between 0 and 1 in accordance 
    with the sigmoid curve."""

    def __init__(self):
        self.output = None

    def forward(self, x):
        self.output = 1/(1 + np.exp(-1*x))
        return True

class SoftMax():
    """This is the SoftMax activation function. It is creates a probability distribution from the values of row vector and is
    especially useful for classification when the target labels are one-hot encoded. Overflow due to exponentation is prevented by
    subtracting the max value of a sample from all its values."""

    def __init__(self):
        self.output = None

    def forward(self, z_array):

        # Overflow prevention,
        z_array -= np.max(z_array, axis = 1, keepdims = True)
        
        self.output = np.exp(z_array) / np.sum(np.exp(z_array), axis = 1, keepdims = True)
        return True

Let us now create a NN. The constructor method of _NeuralNetwork_ will be responsible for the creation of the neural network achitecture and topology as well as the activation functions. The entire forward propagation of the network in specified in _forward_pass_.

In [32]:
input_array = np.array([[1, 2, 3, 2.5],
                        [2.5, 3, 2, 1],
                        [3, 2, 1, 2.5]])

class NeuralNetwork():
    """The class for the neural network model."""

    def __init__(self):
        """Constuctor method. The layers and activation functions of the neural network are created here."""

        # Creating Layers,
        self.LAYER_1 = LayerDense(4, 16)
        self.LAYER_2 = LayerDense(16, 16)
        self.LAYER_3 = LayerDense(16, 4)

        # Creating activations,
        self.ACTIVATION_1 = ReLU()
        self.ACTIVATION_2 = ReLU()
        self.ACTIVATION_3 = SoftMax()

        # Output of the neural network,
        self.output = None

    def forward_pass(self, input_array):
        """The forward propagation of the the feed-forward neural network."""

        # Input layer,
        self.LAYER_1.forward(input_array)
        self.ACTIVATION_1.forward(self.LAYER_1.output)

        # Hidden layer,
        self.LAYER_2.forward(self.ACTIVATION_1.output)
        self.ACTIVATION_2.forward(self.LAYER_2.output)

        # Output layer.
        self.LAYER_3.forward(self.ACTIVATION_2.output)
        self.ACTIVATION_3.forward(self.LAYER_3.output)

        # Setting the output of the NN,
        self.output = self.ACTIVATION_3.output

        # Returning output,
        return self.output


NN = NeuralNetwork()
NN.forward_pass(input_array)
print(NN.output)

[[1.87050169e-31 6.59431246e-34 1.00000000e+00 1.91926152e-24]
 [2.57350217e-29 1.60352196e-31 1.00000000e+00 7.57504439e-23]
 [1.08880981e-31 2.27487633e-34 1.00000000e+00 1.79721279e-24]]
